=== penrose/penrose/packages/examples/src/registry-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/penrose/penrose/main/packages/examples/src/registry-schema.json",
  "title": "Penrose Registry Schema",
  "description": "Schema for the Penrose registry",
  "type": "object",
  "properties": {
    "root": {
      "type": "string",
      "description": "Root URI of the registry"
    },
    "trios": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Human-readable name for trios"
          },
          "substance": {
            "$ref": "#/$defs/substance-key"
          },
          "style": {
            "$ref": "#/$defs/style-key"
          },
          "domain": {
            "$ref": "#/$defs/domain-key"
          },
          "variation": {
            "type": "string",
            "description": "Variation seed"
          },
          "gallery": {
            "type": "boolean",
            "description": "Whether to include in editor gallery"
          }
        },
        "required": ["substance", "style", "domain", "variation"]
      }
    },
    "domains": {
      "type": "object",
      "description": "Map of domains (key is referenced elsewhere)",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "URI": {
            "$ref": "#/$defs/uri"
          }
        }
      }
    },
    "styles": {
      "type": "object",
      "description": "Map of styles (key is referenced elsewhere)",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "URI": {
            "$ref": "#/$defs/uri"
          },
          "domain": {
            "$ref": "#/$defs/domain-key"
          }
        }
      }
    },
    "substances": {
      "type": "object",
      "description": "Map of substances (key is referenced elsewhere)",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "URI": {
            "$ref": "#/$defs/uri"
          },
          "domain": {
            "$ref": "#/$defs/domain-key"
          }
        }
      }
    }
  },
  "required": ["root", "trios", "domains", "substances", "styles"],
  "$defs": {
    "uri": {
      "type": "string",
      "description": "relative path from the root to the file"
    },
    "domain-key": {
      "type": "string",
      "description": "key in `domains`"
    },
    "substance-key": {
      "type": "string",
      "description": "key in `substances`"
    },
    "style-key": {
      "type": "string",
      "description": "key in `styles`"
    }
  }
}

=== penrose/penrose/packages/examples/examples/geometry-domain/registry.json
{
  "root": "https://raw.githubusercontent.com/penrose/penrose/main/examples/geometry-domain",
  "trios": [
    {
      "substance": "c01p01",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c01p10",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c02p01",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c03p01",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c04p01",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c04p12",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c05p01",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c05p13",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c06p06",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c07p02",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c07p06",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c07p10",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c07p22",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c08p08",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c08p18",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c09p02",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c10p08",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c11p07",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c11p12",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c11p21",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c11p25",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c12p12",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "c12p20",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    },
    {
      "substance": "ex",
      "style": "euclidean",
      "domain": "geometry",
      "variation": ""
    }
  ],
  "domains": {
    "geometry": {
      "name": "Geometry",
      "URI": "geometry.dsl"
    }
  },
  "styles": {
    "euclidean": {
      "domain": "geometry",
      "name": "Euclidean 2D Geometry",
      "URI": "euclidean.sty"
    }
  },
  "substances": {
    "c01p01": {
      "domain": "geometry",
      "name": "Collinear Points on Plane",
      "URI": "textbook_problems/c01p01.sub"
    },
    "c01p10": {
      "domain": "geometry",
      "name": "Adjacent Angles",
      "URI": "textbook_problems/c01p10.sub"
    },
    "c02p01": {
      "domain": "geometry",
      "name": "Angle Bisector",
      "URI": "textbook_problems/c02p01.sub"
    },
    "c03p01": {
      "domain": "geometry",
      "name": "Parallel Lines with Marker",
      "URI": "textbook_problems/c03p01.sub"
    },
    "c04p01": {
      "domain": "geometry",
      "name": "Congruent Triangles Inside Quadrilateral",
      "URI": "textbook_problems/c04p01.sub"
    },
    "c04p12": {
      "domain": "geometry",
      "name": "Two Connected Triangles",
      "URI": "textbook_problems/c04p12.sub"
    },
    "c05p01": {
      "domain": "geometry",
      "name": "Nested Triangles with Midsegments",
      "URI": "textbook_problems/c05p01.sub"
    },
    "c05p13": {
      "domain": "geometry",
      "name": "Triangle with Incenter and Right Angle Marker",
      "URI": "textbook_problems/c05p13.sub"
    },
    "c06p06": {
      "domain": "geometry",
      "name": "Parallelogram",
      "URI": "textbook_problems/c06p06.sub"
    },
    "c07p02": {
      "domain": "geometry",
      "name": "Perpendicular Bisectors in Triangle",
      "URI": "textbook_problems/c07p02.sub"
    },
    "c07p06": {
      "domain": "geometry",
      "name": "Prove ABCD is a Parallelogram",
      "URI": "textbook_problems/c07p06.sub"
    },
    "c07p10": {
      "domain": "geometry",
      "name": "Find Orthocenter of Right Angle Triangle",
      "URI": "textbook_problems/c07p10.sub"
    },
    "c07p22": {
      "domain": "geometry",
      "name": "Similar Triangles",
      "URI": "textbook_problems/c07p22.sub"
    },
    "c08p08": {
      "domain": "geometry",
      "name": "Nested Right Angle Triangles",
      "URI": "textbook_problems/c08p08.sub"
    },
    "c08p18": {
      "domain": "geometry",
      "name": "Measures of Triangle",
      "URI": "textbook_problems/c08p18.sub"
    },
    "c09p02": {
      "domain": "geometry",
      "name": "Perpendicular Bisector of Triangle",
      "URI": "textbook_problems/c09p02.sub"
    },
    "c10p08": {
      "domain": "geometry",
      "name": "Triangle Congruency",
      "URI": "textbook_problems/c10p08.sub"
    },
    "c11p07": {
      "domain": "geometry",
      "name": "Circle with Secant",
      "URI": "textbook_problems/c11p07.sub"
    },
    "c11p12": {
      "domain": "geometry",
      "name": "Circle with Chords, Radii, Diameters",
      "URI": "textbook_problems/c11p12.sub"
    },
    "c11p21": {
      "domain": "geometry",
      "name": "Chord Intersection",
      "URI": "textbook_problems/c11p21.sub"
    },
    "c11p25": {
      "domain": "geometry",
      "name": "Trapezoid inside Circle",
      "URI": "textbook_problems/c11p25.sub"
    },
    "c12p12": {
      "domain": "geometry",
      "name": "Circle with Chords, Radii",
      "URI": "textbook_problems/c12p12.sub"
    },
    "c12p20": {
      "domain": "geometry",
      "name": "Triangle Congruency 2",
      "URI": "textbook_problems/c12p20.sub"
    },
    "ex": {
      "domain": "geometry",
      "name": "Congruent Triangles with Markers",
      "URI": "textbook_problems/ex.sub"
    }
  }
}
